daemon off; pid /dev/null; worker_processes auto; error_log /dev/stderr info; events {
        worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;

	client_max_body_size 100M;

	server {
		listen 3000 default_server;
		root /var/www;
		server_name localhost;
		index index.html index.htm;

		# Fuck Google
		add_header Permissions-Policy interest-cohort=();

		location / {
			proxy_pass http://root-website:3000;
		}
	}
}
