### Hent en .ics fil for et enkelt arrangement
GET {{url}}/api/arrangement/dnb-bedpress.ics

### Hent en .ics fil for alle arrangementer
GET {{url}}/api/arrangement

### Hent en .ics fil for alle arrangementer i en kategori
GET {{url}}/api/arrangement?type=bedpres