import { FC } from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Hjem | Root Linjeforening',
    description: 'Generated by create next app', // TODO
}

const Home: FC = () => {
    return (
        <div>
            <h1>Root Linjeforening</h1>
        </div>
    )
}

export default Home;
