import type { Metadata } from "next";
import EventCard from "@/app/components/events/eventCard";
import AdsCard from "@/app/components/events/adsCard";

export const metadata: Metadata = {
    title: 'Hjem | Root Linjeforening',
    description: 'Generated by create next app', // TODO
}

export type Event = {
    _id: string,
    title: string,
    address: string,
    date: string,
    time: string,
    thumbnail: string,
    type: string,
}

export type Ad = {
    _id: string,
    title: string,
    dueDate: string,
    thumbnail: string,
}

const testData: Event[] = [ // TODO testdata skal slettes
    {
        _id: "1",
        title: "Bedriftspresentasjon med Knowit",
        address: "Nøstegaten 58",
        date: "2023-09-21",
        time: "17:00",
        thumbnail: "./next.svg",
        type: "bedriftspresentasjon"
    },
    {
        _id: "2",
        title: "Back 2 School",
        address: "Kronbar",
        date: "2023-09-22",
        time: "18:00",
        thumbnail: "./next.svg",
        type: "sosialt"
    }
]

const testAds: Ad[] = [ // TODO testdata skal slettes
    {
        _id: "1",
        title: "Sommerjobb hos Nav IT",
        dueDate: "2023-09-21",
        thumbnail: "./next.svg",
    }
]


const Home: Component = () => {
    return (
        <div>
            <h1>Root Linjeforening</h1>
            <div className={ "flex flex-wrap justify-around" }>
                <EventCard eventTitle={ "Arrangementer" } events={ testData } showMoreUrl={ "/" }
                           className={ "sm:w-[550px] mx-2" } />
                <AdsCard className={ "sm:w-[550px] mx-2" } ads={ testAds } showMoreUrl={ "/" } />
            </div>
        </div>
    )
}

export default Home;
