name: Remote ssh command
on:
    push:
        branches: ["main"]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd ~/root-web/root-website
                      git pull origin main
                      cd ..
                      docker compose down
                      docker compose build
                      docker compose up -d
