name: Deploy

on:
    push:
        branches: ["main"]

jobs:
    push_to_registry:
        name: Build then push image to Docker Hub
        runs-on: ubuntu-latest
        
        steps:
            - name: Set alternate npm integrity keys
              run: |
                echo COREPACK_INTEGRITY_KEYS="$(curl https://registry.npmjs.org/-/npm/v1/keys | jq -c '{npm: .keys}')" >> $GITHUB_ENV
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: fribyte/root-website

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: ${{ github.event_name == 'push' }}
                  tags: fribyte/root-website:latest
                  build-args: |
                      APP_BUILD_DATE=${{ github.event.repository.updated_at}}
