# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Frontend Build and Push to DockerHub

on:
    push:
        branches: ["main"]

jobs:
    push_to_registry:
        name: Build then push image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: fribyte/root-website

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: ${{ github.event_name == 'push' }}
                  tags: fribyte/root-website:latest
                  build-args: |
                      APP_BUILD_DATE=${{ github.event.repository.updated_at}}
    deploy_to_remote_server:
        name: SSH to server and pull new image
        needs: push_to_registry
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to Remote Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.REMOTE_SERVER_HOST }}
                  username: ${{ secrets.REMOTE_SERVER_USERNAME }}
                  key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
                  script: |
                      cd root-web
                      docker-compose pull rootlinjeforening.no
                      docker-compose up -d
